title = "HardPy TOML config"
tests_name = "Hello HardPy"
sound_on = false
enable_test_pass_fail_modal = false

[database]
user = "dev"
password = "dev"
host = "192.168.30.144"
port = 5984

[frontend]
host = "127.0.0.1"
port = 8000
language = "en"
