title = "HardPy TOML config"
tests_name = "Hello HardPy"
sound_on = false
enable_test_pass_fail_modal = false

[database]
user = "dev"
password = "dev"
host = "100.90.173.76"
port = 5984

[database_frontend]
user = "dev"
password = "dev"
host = "100.90.173.76"
port = 5984

[frontend]
host = "100.90.173.76"
port = 8000
language = "en"
